[dependencies]
base = "0.13.0"

[dev-dependencies]
test = "2.0.0"
fuzz = "0.2.1"

[package]
name = "class-plus"
version = "0.0.1"
description = "Class Plus Helper"
repository = "https://github.com/icdevsorg/class-plus"
keywords = [ "class", "motoko", "helper" ]
