[dependencies]
base = "0.14.14"
itertools = "0.1.2"
vector = "0.4.2"
star = "0.1.1"
rep-indy-hash = "0.1.1"
account = "1.0.1"
icrc1-mo = "0.0.16"
map = "9.0.1"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[package]
name = "icrc2-mo"
version = "0.0.17"
description = "icrc2 for motoko"
repository = "https://github.com/PanIndustrial-Org/icrc2.mo"
keywords = [ "icrc2", "fungible", "token", "standard", "dfinity" ]

[toolchain]
moc = "0.14.14"
