[dependencies]
base = "0.11.0"
itertools = "0.1.2"
star = "0.1.1"
rep-indy-hash = "0.1.1"
account = "1.0.1"
icrc1-mo = "0.0.16"
map = "9.0.1"
vector = "0.4.2"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[package]
name = "icrc4-mo"
version = "0.0.16"
description = "icrc4 for motoko"
repository = "https://github.com/PanIndustrial-Org/icrc4.mo"
keywords = [ "icrc4", "fungible", "token", "standard", "dfinity", "batch" ]

[toolchain]
moc = "0.14.14"
